### ISSUE TITLE
Add sliders for each individual year

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ffvtr#36]
Per Scott/Myron:

> further they would like to manipulate each year (so a slider for each year) from 2019 through 2025 for all three variables. They don't need the ability to type in a number so perhaps that saves room as you just need sliders. 

 > We discussed that that is a lot of sliders 7 for each of 3 variables but that is what they would like if possible; We talked about could we align the sliders in "columns" so that each "row" is a year - that way you are selecting your % change in FTE, Tuition, and State Approps for each year and then you move down to the next row and do the same for that year and so on.

**Comment by cstephen** [comment]
> they would like to manipulate each year (so a slider for each year) from 2019 through 2025 for all three variables

The three variables were currently have are:
- % change student FTEs per year
- Tuition and Fees per Student FTE ($)
- Total State Appropriation (Million $)

Adding three inputs for each year means getting rid of the "% change student FTEs per year" slider that spans all years and making it a "% change since last year" slider for each year, correct?

**Comment by cstephen** [comment]
I think my question is already answered in #32.

**Comment by brucecrevensten** [comment]
Will wait to close this until confirmation from Scott, but it sounds like we don't want to implement this.
